#%RAML 1.0 SecurityScheme

type: Pass Through
description: Require a header for authentication
displayName: Zync Access Token (X-ZYNC-TOKEN)

describedBy:
  headers:
    X-ZYNC-TOKEN:
      type: string

settings:
  signatures: PLAINTEXT
