#%RAML 1.0 DataType

type: object
properties:
  timestamp:
    type: integer
  encryption:
    type: object
    properties:
      type:
        enum: ["AES256-GCM-NOPADDING"]
      iv:
        type: string
      salt:
        type: string
  payload-type:
    enum: ["TEXT", "IMAGE", "VIDEO", "BINARY"]