#%RAML 1.0

title: Zync
version: v1

mediaType: application/json

securitySchemes:
  X-ZYNC-TOKEN: !include security/x-zync-token.raml

types:
  GenericResponse: !include types/responses/GenericResponse.raml
  ClipboardHistory: !include types/responses/ClipboardHistory.raml
  ClipboardList: !include types/responses/ClipboardList.raml
  ClipboardResponse: !include types/responses/Clipboard.raml
  UserAuthenticateResponse: !include types/responses/UserAuthenticateResponse.raml
  UploadURL: !include types/responses/UploadURL.raml
  ClipboardRequest: !include types/requests/Clipboard.raml
  ClipboardRequestWithoutPayload: !include types/requests/ClipboardWithoutPayload.raml
  UserAuthenticate: !include types/requests/UserAuthenticate.raml
  DeviceValidate: !include types/requests/DeviceValidate.raml

securedBy: [X-ZYNC-TOKEN]

/clipboard:
  get:
    description: "Retrieve the latest clipboard contents."
    responses:
      200:
        body:
          type: ClipboardResponse
      204:
        body:
          type: GenericResponse
      400:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      404:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  post:
    description: "Update the clipboard contents."
    body:
      type: ClipboardRequest
    responses:
      200:
        body:
          type: GenericResponse
      400:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  delete:
    description: "Clear the clipboard contents."
    responses:
      200:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  /history:
    get:
      description: "Retrieve the history of previous clipboards."
      responses:
        200:
          body: ClipboardHistory
        401:
          body: GenericResponse

  /raw:
    get:
      description: "Retrieve latest raw clipboard data."
      responses:
        200:
          body:
            text/plain:
        204:
          body:
            type: GenericResponse
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse

  /{timestamp}:
    get:
      description: "Retrieve a clipboard with specific timestamp."
      responses:
        200:
          body:
            type: ClipboardResponse
        204:
          body:
            type: GenericResponse
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse

    /raw:
      get:
        description: "Retrieve raw clipboard data with specific timestamp"
        responses:
          200:
            body:
              text/plain:
          204:
            body:
              type: GenericResponse
          401:
            body:
              type: GenericResponse
          404:
            body:
              type: GenericResponse
          500:
            body:
              type: GenericResponse

  /{timestamp},...:
    get:
      description: "Retrieve list of clipboards with specific timestamps separated by commas."
      responses:
        200:
          body:
            type: ClipboardList
        204:
          body:
            type: GenericResponse
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse
  /upload:
    post:
      description: "Retrieve an upload URL."
      body:
        type: ClipboardRequestWithoutPayload
      responses:
        200:
          body:
            type: UploadURL
        204:
          body:
            type: GenericResponse
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse


/user:
  /authenticate:
    securedBy: []
    post:
      description: "Authenticate a user and send a zync token with a random token to the device using firebase messaging"
      body:
        type: UserAuthenticate
      responses:
        200:
          body: UserAuthenticateResponse
        400:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse

/device:
  /validate:
    post:
      description: "Validate the device and start receiving clipboard notifications"
      body:
        type: DeviceValidate
      responses:
        200:
          body: GenericResponse
        400:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse