#%RAML 1.0

title: Zync
version: v1

mediaType: application/json

securitySchemes:
  X-ZYNC-TOKEN: !include security/x-zync-token.raml

types:
  GenericResponse: !include types/responses/GenericResponse.raml
  ClipboardHistory: !include types/responses/ClipboardHistory.raml
  CallbackToken: !include types/responses/CallbackToken.raml
  ClipboardVerification: !include types/responses/ClipboardVerification.raml
  Clipboard: !include types/requests/Clipboard.raml

securedBy: [X-ZYNC-TOKEN]

/clipboard:
  get:
    description: "Retrieve the latest clipboard contents."
    responses:
      200:
        body:
          application/octet-stream: file
      204:
        body:
          type: GenericResponse
      400:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      404:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  /verify:
    get:
      description: "Retrieve the latest clipboards timestamp and hash."
      responses:
        200:
          body:
            type: ClipboardVerification
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse

  post:
    description: "Update the clipboard contents."
    body:
      type: Clipboard
    responses:
      200:
        body:
          type: GenericResponse
      400:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  delete:
    description: "Clear the clipboard contents."
    responses:
      200:
        body:
          type: GenericResponse
      401:
        body:
          type: GenericResponse
      500:
        body:
          type: GenericResponse

  /history:
    get:
      description: "Retrieve the history of previous clipboards."
      responses:
        200:
          body: ClipboardHistory
        401:
          body: GenericResponse

  /{timestamp}:
    get:
      description: "Retrieve a clipboard with specific timestamp."
      responses:
        200:
          body:
            application/octet-stream: file
        204:
          body:
            type: GenericResponse
        401:
          body:
            type: GenericResponse
        404:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse

    /verify:
      get:
        description: "Retrieve the timestamp and hash with specific timestamp."
        responses:
          200:
            body:
              type: ClipboardVerification
          401:
            body:
              type: GenericResponse
          404:
            body:
              type: GenericResponse
          500:
            body:
              type: GenericResponse

/user:
  /authenticate:
    securedBy: []
    get:
      description: "Retrieve a Zync token"
      responses:
        200:
          body: CallbackToken
        400:
          body:
            type: GenericResponse
        500:
          body:
            type: GenericResponse
      queryParameters:
        token:
          description: "Use a Firebase Token to receive the Zync token"
          type: string